#!/usr/bin/env python3

import sys
from math import *
import math
import time

def errorOutput(message):
    print(message, file=sys.stderr)
    exit(84)

def print_help():
    print("USAGE\n\t./205IQ \u03BC \u03C3 [IQ1] [IQ2]\n")
    print("DESCRIPTION")
    print("\t\u03BC\tpredetermined mean")
    print("\t\u03C3\tpredetermined standard deviation")
    print("\tIQ1\tminimum IQ")
    print("\tIQ2\tmaximum IQ")
    exit(0)

def formula(micro, alpha, increment):
    return ((100 * math.exp(- math.pow(increment - micro, 2) / ((2 * math.pow(alpha, 2))))) / (alpha * math.sqrt(2 * math.pi)))

def formule(micro, alpha, increment):
    return (1 / (float(alpha) * sqrt(2 * pi))) * exp(-(float(increment) - float(micro)) ** 2 / (2 * float(alpha) ** 2))

def formuleAlexis(micro, alpha, increment):
    return (1 / (alpha * math.sqrt(2 * math.pi))) * math.exp(-0.5 * ((micro - float(increment)) / alpha) ** 2)

def calcAllPercentage(micro, alpha):
    i = 0
    for i in range(201):
        print("%d %.5f" % (i, round(formuleAlexis(micro, alpha, i), 5)))

def calcPercentageInferior(micro, alpha, IQ):
    tab = []
    res = 0
    for i in range(201):
        tab.append(((round(formuleAlexis(micro, alpha, i), 5) + (4 * round(formuleAlexis(micro, alpha, i + 0.5), 5)) + round(formuleAlexis(micro, alpha, i + 1), 5)) / 6) * 100)
    for i in range(0, IQ):
        res += tab[i]
    print("%.1f%s of people have an IQ inferior to %s" % (res, "%", IQ))

def calcPercentageBetween(micro, alpha, IQ1, IQ2):
    tab = []
    res = 0
    for i in range(201):
        tab.append(((round(formuleAlexis(micro, alpha, i), 5) + (4 * round(formule(micro, alpha, i + 0.5), 5)) + round(formuleAlexis(micro, alpha, i + 1), 5)) / 6) * 100)
    for i in range(IQ1, IQ2):
        res += tab[i]
    print("%.1f%s of people have an IQ between %s and %s" % (res, "%", str(IQ1), str(IQ2)))

if len(sys.argv) == 2 and sys.argv[1] == "-h":
    print_help()
elif len(sys.argv) == 3:
    try:
        micro = int(sys.argv[1])
        alpha = int(sys.argv[2])
        if micro != 100 or alpha <= 0:
            errorOutput("Invalid arguments. Type ./205IQ -h for help.")
        calcAllPercentage(micro, alpha)
    except:
        errorOutput("Invalid arguments. Type ./205IQ -h for help.")
    exit(0)
elif len(sys.argv) == 4:
    try:
        micro = int(sys.argv[1])
        alpha = int(sys.argv[2])
        IQ1 = int(sys.argv[3])
        if (micro != 100 or alpha <= 0 or IQ1 < 0):
            errorOutput("Invalid arguments. Type ./205IQ -h for help.")
        calcPercentageInferior(micro, alpha, IQ1)
    except:
        errorOutput("Invalid arguments. Type ./205IQ -h for help.")
    exit(0)
elif len(sys.argv) == 5:
    try:
        micro = int(sys.argv[1])
        alpha = int(sys.argv[2])
        IQ1 = int(sys.argv[3])
        IQ2 = int(sys.argv[4])
        if (micro != 100 or alpha <= 0 or IQ1 < 0 or IQ2 <= 0 or IQ2 < IQ1 or IQ1 > 200 or IQ2 > 200):
            errorOutput("Invalid arguments. Type ./205IQ -h for help.")
        calcPercentageBetween(micro, alpha, IQ1, IQ2)
    except:
        errorOutput("Invalid arguments. Type ./205IQ -h for help.")
    exit(0)
else:
    errorOutput("Not enough arguments. Type ./205IQ -h for help.")